version: "3.7"

services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - db.env # configure postgres
    ports:
      - '5432:5432'
    volumes:
      - save-data:/var/lib/postgresql/data/ # persist data even if container shuts down
  
  rabbitmq:
    image: "bitnami/rabbitmq:3.7"
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/bitnami"

  redis:
    image: "bitnami/redis:5.0.4"
    env_file:
      - redis.env
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"

  celery-flower:
    image: gregsi/latest-celery-flower-docker:latest
    env_file:
      - amqp.env
    ports:
      - "5555:5555"
    depends_on:           # express dependency between services
      - rabbitmq
      - redis

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - "./:/app"
    command: "poetry run hypercorn app/app/main:app --bind 0.0.0.0:8000 --reload"

  worker:
    build: .
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - "./:/app"
    command: "poetry run celery worker -A app.app.worker.celery_worker -l info -Q test-queue -c 1"
    
volumes:
  save-data: 
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
